-- Active: 1704940130171@@127.0.0.1@3306
CREATE DATABASE demo_ajax;
use demo_ajax;

create table student(
    student_id int PRIMARY KEY AUTO_INCREMENT,
    student_name VARCHAR(45)
);

-- Add 100 data rows to the student table
INSERT INTO student (student_name) VALUES
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),('Student 1'),
('Student 2'),
('Student 3'),
('Student 4'),
('Student 100');